### ISSUE TITLE
Fill in year/name of license

### ISSUE THREAD

**Issue by Apanatshka** [MetaBorgCube/metaborg-api-usage#4]
Currently the LICENSE file has `Copyright {yyyy} {name of copyright owner}`...

**Comment by Gohla** [comment]
LICENSE does not have copyright information, that is just text that explains how to apply the Apache license. Copyright information should go into the NOTICE file, which was missing but which I just copied from the spoofax repository. You can update it with additional Oracle copyright information if needed.
